// 转发壳（实现落在 .cjs：平台运行时禁用 require(ESM)，只有 .cjs 两边都能装载）
export {
  SHARE_VERSION,
  VISIBILITIES,
  REVIEW_STATES,
  DEFAULT_VISIBILITY,
  DEFAULT_REVIEW_STATE,
  REVIEW_NOTE_MAX,
  VISIBILITY_LABELS,
  REVIEW_LABELS,
  MODEL_FIELDS,
  ACTIONS,
  OWNER_ACTIONS,
  ADMIN_ACTIONS,
  actionBy,
  isValidVisibility,
  isValidReviewState,
  shareOf,
  effectiveVisibility,
  canView,
  applyShareAction,
  authorNameOf,
  shareView,
  shareSummary,
  actionsFor,
} from './modelshare.cjs';
